server:
  port: 8761

spring:
  application:
    name: EUREKASERVER
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true

zuul:
  sensitive-headers:
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
  routes:
    eureka-client:
      path: /eureka-client/**
      url: http://localhost:8081
    springboot-demo:
      path: /springboot-demo/**
      url: http://localhost:8080

logging:
  level:
    com:
      netflix:
        config:
          sources:
            URLConfigurationSource: ERROR